# MMOCR Detection Model Configuration List
# Optimized batch sizes - Adaptive binary search
# Config files already updated with optimal batch sizes

# TEXTSNAKE models
- configs/textdet/textsnake_custom/textsnake_cegdr.py

# PSENET models
- configs/textdet/psenet_custom/psenet_cegdr.py

# PANET models
- configs/textdet/panet_custom/panet_cegdr.py

# DBNETPP models
- configs/textdet/dbnetpp_custom/dbnetpp_cegdr.py

# FCENET models
- configs/textdet/fcenet_custom/fcenet_cegdr.py

# DBNET models
- configs/textdet/dbnet_custom/dbnet_cegdr.py

