# Configuration for roboflow_head_demo.py (image + depth processing)

# Input directories
input_img_dir: "data/3d_cattle_demo/renders/cow_boxed/sliding_clip_120s_v3/case=default/render=image/front_upper/2025-08-04_203708"
input_depth_dir: "data/3d_cattle_demo/renders/cow_boxed/sliding_clip_120s_v3/case=default/render=depth/front_upper/2025-08-05_173119"

# Model configuration
model:
  model_id: "cow-heads-varied-heoza/2"
  api_url: "http://127.0.0.1:9001"

# Defaults
defaults:
  font_size: 0.5
  confidence_threshold: 0.85
  iou_threshold: 0.01

# Output configuration
output:
  base_dir: "data/bonting-identification/processed_images/tracking_heads"
  remove_input_prefix: "data/"