# Configuration for roboflow_head_demo.py
# Cow Head Tracking Model Settings

# Video Configuration
video:
  input_path: "data/3d_cattle_demo/renders/cow_boxed/sliding_clip_120s_v3/case=default/render=image/front_upper/2025-08-04_203708/baseline-1-120.mp4"
  test_video_duration: 5
  test_video_name: "test_video_head_tracking.mp4"

# Model Configuration
model:
  model_id: "cow-heads-varied-heoza/2"
  api_url: "http://127.0.0.1:9001"

# Default Head Tracking Settings
defaults:
  font_size: 0.5
  confidence_threshold: 0.85
  iou_threshold: 0.01  # IoU threshold for Non-Maximum Suppression
  duration: null  # null (1 frame), 'full' (all frames), or float (seconds)

# Output Configuration
output:
  base_dir: "data/bonting-identification/processed_videos/tracking_heads"
  remove_input_prefix: "data/"