# Configuration for roboflow_head_demo.py
# Cow Head Tracking Model Settings

# Video Configuration
video:
  input_path: "data/HF_dataset/source_videos/youtube_segments/Milking R Dairy - Nedap CowControl with the SmartTag Ear clipped.mp4"
  test_video_duration: 5
  test_video_name: "test_video_head_tracking.mp4"

# Model Configuration
model:
  model_id: "cow-heads-varied-heoza/2"
  api_url: "http://127.0.0.1:9001"

# Default Head Tracking Settings
defaults:
  font_size: 0.5
  confidence_threshold: 0.1
  duration: null  # null (1 frame), 'full' (all frames), or float (seconds)

# Output Configuration
output:
  base_dir: "data/HF_dataset/processed_videos/tracking_heads"
  model_tag: "roboflow_tracking_heads"