name: bonting-exp
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - tqdm
  - streamlit
  - py-opencv
  - pytorch
  - torchvision
  - pip:
      - ultralytics>=8.2.0
      - yt-dlp
      - huggingface_hub[hf_xet,cli]
      - kagglehub
      - pillow
      - transformers
