name: bonting-id
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas
  - tqdm
  - streamlit
  - pytorch
  - torchvision
  - pip:
      - opencv-python
      - ipywidgets
      - ipykernel
      - ultralytics>=8.2.0
      - yt-dlp
      - huggingface_hub[hf_xet,cli]
      - kagglehub
      - "mlflow[databricks]>=3.1"
      - python-dotenv
      - pillow
      - transformers
      - roboflow
      - supervision
