name: bonting-exp
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - tqdm
  - streamlit
  - opencv
  - pip:
    - torch
    - torchvision
    - ultralytics>=8.2.0
    - opencv-python-headless
    - yt-dlp
    - huggingface_hub[hf_xet,cli]