name: bonting-id
channels:
  - conda-forge            # only one channel → smaller, faster solves
dependencies:
  - python =3.11
  - pytorch-gpu =2.4.*     # CUDA build chosen automatically
  - opencv >=4.10,<4.11
  - torchvision
  - transformers
  - huggingface_hub
  - cudatoolkit =11.8      # runtime libraries inside the env
  - ipykernel
  - ipywidgets
  - numpy <2
  - pandas
  - tqdm
  - streamlit
  - imgaug
  - pip:
      - numpy <2
      - easyocr
      - ultralytics>=8.2.0
      - kagglehub
      - "mlflow[databricks]>=3.1"
      - streamlit-tree-select
      - openmim
      - python-dotenv
      - pillow
      - yt-dlp
      - inference
      - inference-sdk
