name: bonting-id
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas
  - tqdm
  - streamlit
  - pytorch
  - torchvision
  - opencv<=4.10.0.84 # supports h.264 codec (.mp4 read/write) for versions > 4.10
  - ipywidgets
  - ipykernel
  - yt-dlp
  - huggingface_hub
  - python-dotenv
  - pillow
  - transformers
  - supervision
  - easyocr
  - pip:
      - ultralytics>=8.2.0
      - kagglehub
      - "mlflow[databricks]>=3.1"
      - inference
      - inference-sdk
      - inference-cli
