# environment.yml  (name it whatever you like)
name: bonting-id
channels:
  - conda-forge          # one channel → deterministic, quick solves
dependencies:
  - python=3.11

  - papermill
  - mlflow
  - ipykernel
  - ipywidgets
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu118
    - torch==2.1.0+cu118
    - torchvision==0.16.0+cu118
    # - transformers

    # - huggingface_hub
    - numpy<2
    # - pandas
    - tqdm
    # - streamlit
    # - imgaug
    # - openmim
    # - easyocr
    # - ultralytics>=8.2.0
    # - kagglehub
    # - "mlflow[databricks]>=3.1"
    # - streamlit-tree-select
    # - pillow
    # - yt-dlp
    - python-dotenv
    - inference
    - inference-sdk
    - openmim
